{% set name = "omnicloudmask" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/omnicloudmask-{{ version }}.tar.gz
  sha256: ccec81b44f97251faf6eac77d0f6c4f646444d298d1803089bb1922ed6b13792

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fastai >=2.7
    - gdown >=5.1.0
    - huggingface_hub >=0.28.1
    - rasterio >=1.3
    - safetensors >=0.3.0
    - timm >=0.9
    - pytorch >=2.2.0
    - tqdm >=4.0
    - thinc >=8.3.4
    - platformdirs >=4.0.0

test:
  imports:
    - omnicloudmask
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DPIRD-DMA/OmniCloudMask
  summary: Python library for cloud and cloud shadow segmentation in high to moderate resolution satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wrignj08
    - giswqs
